---
title: "ExitTime"
author: "Roland Stroop"
date: '2023-12-14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Import Libraries
```{r}
library(tidyverse)
library(dplyr)
library(latex2exp)
```

# Include CSV
```{r}
# UNCOMMENT either of the scenario value assignment  to compute the plot of each scenario
scenarios <- c("Global Alarming - Random Exit", "Global Alarming - Nearest Exit")
#scenarios <- c("Range Alarming - Random Exit", "Range Alarming - Nearest Exit" )

labels <- c("Panic", "Emergency Plan")
stopifnot(length(scenarios) == length(labels))
```


```{r readfile}
read_exit_times <- function(scenario_name) {
  times <- c()
  
  filesEmerg <- list.files("../reports_final", pattern=sprintf(r'{Escape_the_MI-%s.*EmergencyReport.txt}', scenario_name), full.names=TRUE)
  filesHosts <- list.files("../reports_final", pattern=sprintf(r'{Escape_the_MI-%s.*NumberOfHostsReport.txt}', scenario_name), full.names=TRUE)

  stopifnot(length(filesEmerg)==length(filesHosts)) # ! es fehlt oder gibt mind. einen Report zu viel/wenig
  
  for (i in seq(length(filesEmerg))) {

    csv_emerg <-  read.csv(filesEmerg[i], skip=1, header=FALSE, col.names=c("node", "exit", "absolute", "relative")) %>% drop_na(relative)
    csv_hosts <-  read.csv(filesHosts[i], header=FALSE, col.names=c("nrofhosts"))

    #print(paste(scenario_name, i, filesEmerg[i], length(csv_emerg$relative)))
    stopifnot(length(csv_emerg$relative) == csv_hosts$nrofhosts) # ! nicht alle Nodes haben einen Exit erreicht
    times <- c(times, max(csv_emerg$relative))
    #
    #print(max(csv_emerg$relative))
  }
  return(times)
}
# read_exit_times("Range Alarming - Nearest Exit")
```

```{r}
values <- c()
names <- c()

for (i in seq(length(scenarios))) {
  val <- read_exit_times(scenarios[i])
  values <- c(values, val)
  names <- c(names, rep(labels[i], length(val))) # str_split(s, pattern=" - ")[[1]][2]
}

exitData <- data_frame(values, names)

pdf(paste0("boxplot_", str_split(scenarios[i][1], pattern=" - ")[[1]][1], ".pdf"), width = 8, height = 5.5, pointsize=14) # "boxplot_InRangeAlarming.pdf",  "boxplot_globalAlarming.pdf"
boxplot(exitData$values ~ exitData$names, 
        ylab=TeX("Time until last person left the building [s]"), 
        #xlab=TeX("Scenarios"),
        yaxt="n",
        xlab="",
        col=hcl.colors(length(scenarios)+1, palette = "RdYlBu"))
axis(side = 2,
     ## Rotate the labels.
     las = 2)

dev.off()
```
