---
title: "Evaluation"
author: "Roland Stroop"
date: '2023-12-14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Import Libraries
```{r}
library(tidyverse)
library(dplyr)
library(latex2exp)
```

# Include CSV
```{r}
scenarios <- c("Global Alarming - Nearest Exit", "Global Alarming - Random Exit", "Range Alarming - Nearest Exit", "Range Alarming - Random Exit")
scenario_name <- scenarios[4] # CHANGE the index [1-4] to compute the plot of each scenario
```

```{r readfile}
file_exit     <- list.files("../reports", pattern=sprintf(r'{Escape_the_MI-%s.*-3-.*EmergencyReport.txt}', scenario_name), full.names=TRUE)
file_nrofHost <- list.files("../reports", pattern=sprintf(r'{Escape_the_MI-%s.*-3-.*NumberOfHostsReport.txt}', scenario_name), full.names=TRUE)

stopifnot(length(file_exit) == 1)
stopifnot(length(file_nrofHost) == 1)

csv_exits     <-  read.csv(file_exit, skip=1, header=FALSE, col.names=c("node", "exit", "absolute", "relative"))
csv_nrofHosts <-  read.csv(file_nrofHost, header=FALSE, col.names=c("nrofhosts"))
```

# Include CSV
```{r readfile}
data_exit <- csv_exits %>%
  group_by(exit) %>%
  arrange(relative) %>%
  mutate(number = row_number()) %>%
  ungroup()

data_main <- csv_exits %>%
  arrange(relative) %>%
  mutate(number = csv_nrofHosts$nrofhosts-row_number()) %>%
  mutate(exit="MI Building") %>%
  add_row(exit="MI Building", node="-", relative=0, absolute=0, number=csv_nrofHosts$nrofhosts, .before=1)

data <- rbind(data_main, data_exit)
```

# Plot
```{r}
pdf(file=paste0("plot_", scenario_name, ".pdf"), width = 8, height = 5.5, pointsize=14) 
plot(x=data$relative, y=data$number, xlab=TeX("Time since emergency event [s]"), ylab=TeX("Number of students"), col=rgb(0.2,0.1,0.5,0.9), type="n", yaxt="n")

exits <- c("MI Building", "Northern Exit", "Southern Exit", "Western Exit")
for (i in seq(exits)) {
  exit_name <- exits[i]
  tmp <- data %>% filter(exit == exit_name)

  lines(tmp$relative, tmp$number, lty=i, type="l")
  if (i == 1) {
    color = rgb(92/255, 65/255, 115/255, 0.2)
  } else {
    color = rgb(0.2,0.1,0.5,0.2)
  }
  polygon(c(min(tmp$relative), tmp$relative, max(tmp$relative)),
      c(0, tmp$number, 0),
      col=color, border=FALSE)
}
legend('topright', 
     legend=TeX(sprintf(r'(%s)', exits)), 
     #fill="red",
     lwd=1, 
     lty=seq(exits))


axis(side = 2,
     ## Rotate the labels.
     las = 2)
dev.off()
```



